# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('account_balance', models.CharField(max_length=100000000)),
                ('account_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=5)),
                ('street_name', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=18)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSB', models.CharField(max_length=6)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_mailing_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('contactID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('customer_description', models.CharField(max_length=1000)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Account')),
                ('contactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('loginID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=2)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transferID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=10)),
                ('transfer_description', models.CharField(max_length=140)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Account')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='contactID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ContactDetails'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_BSB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Bank'),
        ),
    ]
